channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pandas=1.4.4
  - numpy=1.22.4
  - pip:
      - mlflow==2.8.1
      - azureml-mlflow==1.51.0
      - cloudpickle==2.2.1
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
